name: ChunkyBorder
version: ${project.version}
main: org.popcraft.chunkyborder.ChunkyBorder
api-version: "1.13"
depend: [Chunky]
softdepend: [dynmap, BlueMap, Pl3xMap]
load: POSTWORLD
authors: [pop4959]
description: Add a world border to your Chunky world
website: https://github.com/pop4959/ChunkyBorder
commands:
  chunkyborder:
    description: Set a border
    aliases: [cb]
    permission: chunkyborder.chunkyborder
    usage: /chunkyborder <add|remove>
permissions:
  chunkyborder.chunkyborder:
    description: Set a border
    default: op
  chunkyborder.bypass.move:
    description: Bypass border movement checks
    default: false
  chunkyborder.bypass.place:
    description: Bypass border block placement checks
    default: false
